### ISSUE TITLE
stange bug  if(channel._typing.has(user.id)) { TypeError: Cannot read properties of undefined (reading 'has')

### ISSUE THREAD

**Issue by ReedeB** [Senither/hypixel-discord-chat-bridge#55]

**Comment by ReedeB** [comment]
C:\Users\19206\Documents\hypixel-discord-chat-bridge\node_modules\discord.js-light\actions.js:561
                if(channel._typing.has(user.id)) {
                                   ^

TypeError: Cannot read properties of undefined (reading 'has')
    at TypingStart.client.actions.TypingStart.handle (C:\Users\19206\Documents\hypixel-discord-chat-bridge\node_modules\discord.js-light\actions.js:561:22)
    at Object.PacketHandlers.TYPING_START (C:\Users\19206\Documents\hypixel-discord-chat-bridge\node_modules\discord.js-light\handlers.js:238:29)
    at WebSocketManager.client.ws.handlePacket (C:\Users\19206\Documents\hypixel-discord-chat-bridge\node_modules\discord.js-light\actions.js:38:28)
    at WebSocketShard.onPacket (C:\Users\19206\Documents\hypixel-discord-chat-bridge\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\19206\Documents\hypixel-discord-chat-bridge\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\19206\Documents\hypixel-discord-chat-bridge\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (C:\Users\19206\Documents\hypixel-discord-chat-bridge\node_modules\ws\lib\websocket.js:970:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (C:\Users\19206\Documents\hypixel-discord-chat-bridge\node_modules\ws\lib\receiver.js:517:14)
    
    
    This happened at random times and I cant seem to fix it.
